---
title: "Data Dictionary"
output: github_document
---

```{r, load-libraries, message = FALSE, warning = FALSE, echo = FALSE}
library(dplyr) # For data manipulation
library(sf) # For working with spatial data
library(data.table)
# # install package from github
# library(devtools)
# devtools::install_github("heba-razzak/createDataDict")
library(createDataDict)
```

```{r, read-osm-roads, message=FALSE, warning=FALSE, echo=FALSE, eval=TRUE}
# osm file directory
file_directory = readr::read_file("inputs/osm_directory.txt")

# read roads file
sanfrancell_roads <- st_read(paste0(file_directory,"/sanfrangrid_roads_osm.shp"), quiet = TRUE)

# get dataframe for descriptions
descriptions <- descriptions_df(sanfrancell_roads)

# update descriptions dataframe
descriptions <- update_description(descriptions,
                                   c("osm_id", "name", "highway", "lanes", "maxspeed", "geom"),
                                   c("Unique Identifier from OpenStreetMap",
                                     "Name of the entity",
                                     "Type of road",
                                     "Number of lanes",
                                     "Maximum speed",
                                     "Geometry information"))
# Print data dictionary
print_data_dict(sanfrancell_roads, data_title="OSM Roads", descriptions=descriptions)
```

```{r, purpleair, echo=FALSE, eval=TRUE}
# directory containing all monthly and full purpleair files
file_directory = readr::read_file("inputs/purpleair_directory.txt")
# Read purple air data (get filename for full data then read it)
# from smallest date in folder to largest date
file_paths <- list.files(file_directory, pattern = "purple_air_sanfran_.*.csv", full.names = FALSE)
from = "9999-99-99"
to = "0000-00-00"
for (f in file_paths) {
  from = min(from,substr(f,20,29))
  to = max(to,substr(f,31,40))
}
purpleair <- read.csv(paste0(file_directory,"/purple_air_sanfran_", from, "_", to, ".csv"))

# get dataframe for descriptions
descriptions <- descriptions_df(purpleair)

# update descriptions dataframe
descriptions <- update_description(descriptions,
                                   c("time_stamp",
                                     "pm2.5_atm",
                                     "pm2.5_atm_a",
                                     "pm2.5_atm_b",
                                     "sensor_index"),
                                   c("Timestamp of measurement",
                                     "Returns ATM variant average for channel A and B but excluding downgraded channels. Estimated mass concentration PM2.5 (ug/m3). PM2.5 are fine particulates with a diameter of fewer than 2.5 microns.",
                                     "PM2.5 concentration in atmosphere (ug/m^3) - channel A",
                                     "PM2.5 concentration in atmosphere (ug/m^3) - channel B",
                                     "Sensor index"))

# Print data dictionary
print_data_dict(purpleair, data_title="Purple Air 2018-2019", descriptions=descriptions)
```

```{r, uber-speeds, echo=FALSE, eval=TRUE}
file_directory = readr::read_file("inputs/uber_directory.txt")

uber_speeds <- fread(paste0(file_directory,"/movement-speeds-hourly-san-francisco-2018-1.csv"))

# get dataframe for descriptions
descriptions <- descriptions_df(uber_speeds)

# update descriptions dataframe
descriptions <- update_description(descriptions,
                                   c("year", "month", "day", "hour", "utc_timestamp", "segment_id",
                                     "start_junction_id", "end_junction_id", "osm_way_id",
                                     "osm_start_node_id", "osm_end_node_id", "speed_mph_mean",
                                     "speed_mph_stddev"),
                                   c("Year",
                                     "Month",
                                     "Day",
                                     "Hour",
                                     "Date & time of observations in UTC format",
                                     "Special Ids assigned to road segments by Uber",
                                     "Junction where the segment starts i.e., a roundabout",
                                     "Junction where the segment ends",
                                     "OSM Way Id with One to Many relationship with segment_id",
                                     "Start node Id of OSM corresponding to start_junction_id",
                                     "End node Id of OSM corresponding to end_junction_id",
                                     "Mean speed of vehicles within an hour",
                                     "Standard deviation of speed of vehicles in an hour"))


# Print data dictionary
print_data_dict(uber_speeds, 
                data_title="Uber Speeds 2018/01 (as downloaded from uber)", 
                descriptions=descriptions)
```

```{r, uber-2018, echo=FALSE, eval=TRUE}
file_directory = readr::read_file("inputs/uber_directory.txt")

uber_speeds <- fread(paste0(file_directory,"/uber_2018.csv"))

# get dataframe for descriptions
descriptions <- descriptions_df(uber_speeds)

# update descriptions dataframe utc_timestamp,osm_way_id,speed_mph_mean
descriptions <- update_description(descriptions,
                                   c("utc_timestamp", 
                                     "osm_way_id", 
                                     "speed_mph_mean"),
                                   c("Date & time of observations in UTC format",
                                     "OSM Way Id with One to Many relationship with segment_id",
                                     "Mean speed of vehicles within an hour"))

# Print data dictionary
print_data_dict(uber_speeds, 
                data_title="Uber Speeds 2018 (selected columns)", 
                descriptions=descriptions)
```

```{r, uber-2019, echo=FALSE, eval=TRUE}
file_directory = readr::read_file("inputs/uber_directory.txt")

uber_speeds <- fread(paste0(file_directory,"/uber_2019.csv"))

# get dataframe for descriptions
descriptions <- descriptions_df(uber_speeds)

# update descriptions dataframe utc_timestamp,osm_way_id,speed_mph_mean
descriptions <- update_description(descriptions,
                                   c("utc_timestamp", 
                                     "osm_way_id", 
                                     "speed_mph_mean"),
                                   c("Date & time of observations in UTC format",
                                     "OSM Way Id with One to Many relationship with segment_id",
                                     "Mean speed of vehicles within an hour"))

# Print data dictionary
print_data_dict(uber_speeds, 
                data_title="Uber Speeds 2019 (selected columns)", 
                descriptions=descriptions)
```

```{r, df_example, echo=FALSE, eval=FALSE}
# get dataframe for descriptions
descriptions <- descriptions_df(df)

# update descriptions dataframe
descriptions <- update_description(descriptions,
                                   c(""),
                                   c(""))

# Print data dictionary
print_data_dict(df, data_title="df", descriptions=descriptions)
```
