---
title: "Preprocessing PurpleAir Plots"
output: github_document
---

# Clean PurpleAir data points

```{r setup, include=FALSE}
purpleair_directory <- readr::read_file("inputs/purpleair_directory.txt")
preprocessing_directory <- readr::read_file("inputs/preprocessing_directory.txt")
```

## Load required libraries
```{r, load-libraries, message = FALSE, warning = FALSE}
library(dplyr) # For data manipulation
library(data.table) # Faster than dataframes (for big files)
library(ggplot2) # Plots
library(sf) # Shapefiles
```

## Read files
```{r, read-files, eval=TRUE}
purpleair_sensors <- st_read(paste0(purpleair_directory, "/purpleair_sensors.gpkg"), quiet = TRUE)
purpleair_filtered_subset <- fread(paste0(preprocessing_directory, "/purpleair_filtered_2018-2019.csv"))
```

# Plot each sensor
```{r sensor-plots, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
# Function to create a plot for a single sensor
plot_sensor <- function(sensor_id) {
  sensor_data <- purpleair_filtered_subset %>% filter(sensor_index == sensor_id)
  
  ggplot(sensor_data, aes(x = time_stamp, y = pm2.5_atm)) +
    geom_line() +
    labs(
      x = "Date", 
      y = "PM2.5 ATM", 
      title = paste("PM2.5 Levels Over Time for Sensor", sensor_id)
    ) +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      plot.title = element_text(hjust = 0.5)
    )
}

# List of unique sensor indices
sensor_ids <- unique(purpleair_filtered_subset$sensor_index)

# Generate and print each plot in the markdown file
for (sensor_id in sensor_ids) {
  print(plot_sensor(sensor_id))
}
```


