---
title: "Uber Speeds Map"
output:
  html_document:
    df_print: paged
---

```{r}
suppressPackageStartupMessages({
  library(dplyr) # For data manipulation
  library(sf) # For working with spatial data
  library(mapview) # For interactive maps
  library(osmdata) # Open Street Map
  library(data.table)
})
```

## crashes - read all uber files and combine to 1
```{r}
# dir = '/Users/heba/Desktop/Uni/Lim Lab/Uber/Speeds'
# setwd(dir)
# # list files in working directory
# file_list <- list.files()
# # fread all files from directory
# data_list <- lapply(file_list, fread)
# # combine data to 1 file
# combined_data <- do.call(rbind, data_list)
```

## read 1 uber file 
```{r}
dir = '/Users/heba/Desktop/Uni/Lim Lab/Uber/Speeds'
setwd(dir)
uber <- fread("movement-speeds-hourly-san-francisco-2019-1.csv")
uber_osm_ids <- unique(uber$osm_way_id)
```
## read osm file for san francisco area
```{r}
output_directory <- "/Users/heba/Desktop/Uni/Lim Lab/OSM"
output_file <- file.path(output_directory, "sanfranarea_roads_osm.shp")
merged_sf <- st_read(output_file)
```
## only keep map area with uber roads
```{r}
uber_osm <- merged_sf[merged_sf$osm_id %in% uber_osm_ids, ]
# Save the sf object as a shapefile
output_directory <- "/Users/heba/Desktop/Uni/Lim Lab/OSM"
output_file <- file.path(output_directory, "ubersanfran_roads_osm.shp")
st_write(uber_osm, output_file, append=FALSE)
```

## read uber map file
```{r}
output_directory <- "/Users/heba/Desktop/Uni/Lim Lab/OSM"
output_file <- file.path(output_directory, "ubersanfran_roads_osm.shp")
uber_osm <- st_read(output_file)
```
## view map
```{r}
mapview(uber_osm)
```
