---
title: "Uber Speeds data"
output: github_document
knit: (function(input, ...) {rmarkdown::render(input, output_dir = "../docs", )})
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.path = "../docs/plots/")
```

```{r, github-package, include=FALSE}
if (!"DataOverviewR" %in% rownames(installed.packages())) {
  suppressMessages({devtools::install_github("heba-razzak/DataOverviewR")})
}
```

Load required libraries

```{r, load-libraries, message = FALSE, warning = FALSE}
library(dplyr)         # Data manipulation
library(data.table)    # Working with large files
library(DataOverviewR) # Data dictionary and summary
```

```{r, read-uber, echo = FALSE}
uber201801 <- fread(file.path("data", "raw", "Uber", "Speeds", "movement-speeds-hourly-san-francisco-2018-1.csv"))
```

---

**Data Dictionary**

```{r, speeds-data-dict, echo = FALSE}
# utc_timestamp - Date & time of observations in UTC format
# segment_id - Special Ids assigned to road segments by Uber
# start_junction_id - Junction where the segment starts i.e., a roundabout
# end_junction_id - Junction where the segment ends
# speed_mph_mean - Mean speed of vehicles within an hour
# speed_mph_stddev - Standard deviation of speed of vehicles in an hour
# The above columns can uniquely identify a street segment and its speed. However, since the segments and junctions correspond to Uber's internal identification models. There also exists Open Street Map (OSM) Ids, that correspond to OSM Way Id and OSM Node Id respectively.
# 
# OSM Way and Node Ids define roads and nodes connecting them. Uber has its own implementation of road structures because speeds can vary a lot within a single OSM Way Id. That is why multiple Segment Ids correspond to a single OSM Way Id. Fortunately, OSM Ids are also provided in the same table
# 
# osm_way_id - OSM Way Id with One to Many relationship with segment_id
# osm_start_node_id - Start node Id of OSM corresponding to start_junction_id
# osm_end_node_id - End node Id of OSM corresponding to end_junction_id

# The datasets contain hourly speed observations of three months. In Open Street Map (OSM), a way defines a line connecting two nodes e.g., a street or a road. Whereas OSM nodes are the points in real world such as a junction. For the speed analysis, a street can be uniquely identified via osm_way_id, osm_start_node_id, and osm_end_node_id. Note that we need all three parameters to identify a street speed because a street can be one way or two way. In case of later, osm-way-id will be the same for both ways but their node ids would swap.
# 
# Mean Speeds in miles per hour are provided per hour. But in the dataset, their are missing values and data is not available for each hour.
desc <- data_description(uber201801, var_desc = c(
  "year" = "Year.",
  "month" = "Month.",
  "day" = "Day.",
  "hour" = "Hour in 24-hour format.",
  "utc_timestamp" = "Timestamp in Coordinated Universal Time (UTC)",
  "segment_id" = "Unique identifier for the road segment on which the speed is measured.",
  "start_junction_id" = "Unique identifier for the starting junction (node) of the road segment.",
  "end_junction_id" = "Unique identifier for the ending junction (node) of the road segment.",
  "osm_way_id" = "OpenStreetMap (OSM) ID for the road segment or way.",
  "osm_start_node_id" = "OpenStreetMap (OSM) ID for the starting node of the segment.",
  "osm_end_node_id" = "OpenStreetMap (OSM) ID for the ending node of the segment.",
  "speed_mph_mean" = "Mean speed in miles per hour recorded on the segment during the observation period.",
  "speed_mph_stddev" = "Standard deviation of the speed in miles per hour recorded on the segment during the observation period."
))
data_dictionary(uber201801, data_title = "Uber Movement Speeds - Jan 2018", descriptions = desc, hide = c("top_n", "NA_Percentage", "NA_Count", "n_unique"))
```

**View data**

```{r, view-speeds, echo = FALSE}
knitr::kable(head(uber201801, 3),
             row.names = FALSE,
             format = "markdown")

# remove to free up memory
rm(uber201801)
```

---

Filter Uber dataset to roads around PurpleAir sensors (to reduce data size)

```{r, filter-uber}
# read uber data

# osm ids for filtering
filepath <- file.path("data", "raw", "bayarea_osm_roads.gpkg")
osm_roads <- sf::st_read(filepath, quiet = TRUE) %>% pull(osm_id) %>% unique()

# filter uber data
uber2018 <- fread(file.path("data", "raw", "uber_2018.csv")) %>% filter(osm_way_id %in% osm_roads)
uber2019 <- fread(file.path("data", "raw", "uber_2019.csv")) %>% filter(osm_way_id %in% osm_roads)

uber <- rbindlist(list(uber2018,uber2019))

rm(uber2018, uber2019)

# Error in `filter()`:
# ℹ In argument: `osm_way_id %in% osm_roads`.
# Caused by error:
# ! vector memory exhausted (limit reached?)
# Backtrace:
#  1. fread(file.path("data", "raw", "uber_2019.csv")) %>% ...
#  9. osm_way_id %in% osm_roads
# Execution halted
```

```{r, echo = FALSE}
# jan 2018:
# before: 24,074,530
# after: 12,916,574
```

Uber Speeds has `r format(nrow(uber2018) + nrow(uber2019), big.mark = ",")` rows for 2018 and 2019.

After filtering, Uber Speeds has `r format(nrows(uber), big.mark = ",")` rows.

---

**Data Dictionary**

```{r, uber-data-dict, echo = FALSE}
desc <- data_description(uber, var_desc = c(
  "utc_timestamp" = "Timestamp in Coordinated Universal Time (UTC)",
  "osm_way_id" = "OpenStreetMap (OSM) ID for the road segment or way.",
  "speed_mph_mean" = "Mean speed in miles per hour recorded on the segment during the observation period."
))
data_dictionary(uber, data_title = "Uber Movement Speeds - Jan 2018", descriptions = desc, hide = c("top_n", "NA_Percentage", "NA_Count", "n_unique"))
```

**View data**

```{r, view-uber, echo = FALSE}
knitr::kable(head(uber, 3),
             row.names = FALSE,
             format = "markdown")
```

---
