---
title: "Exploratory Data Analysis: Air Quality System" 
output: github_document
knit: (function(input, ...) {rmarkdown::render(input, output_dir = "../docs", )})
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(fig.path = "../docs/plots/")
options(scipen = 999) 
```

```{r, github-packages, echo=FALSE}
if (!"DataOverviewR" %in% rownames(installed.packages())) {
  suppressMessages({devtools::install_github("heba-razzak/DataOverviewR")})
}
```

United States Environmental Protection Agency: Air Quality System (AQS)

```{r, load-libraries, message = FALSE, warning = FALSE, echo = FALSE}
library(dplyr)         # Data manipulation
library(DataOverviewR) # Data dictionary and summary
```

```{r, read-aqs, echo = FALSE}
aqs_data <- read.csv(file.path("data", "raw", "EPA_airquality.csv"))
```

---

**Data Summary**

```{r, data-summ, echo = FALSE}
data_summary(aqs_data, data_title = "AQS Summary")
```

---

Histograms for numerical columns

```{r, hist, echo = FALSE}
numeric_cols <- names(aqs_data)[sapply(aqs_data, is.numeric)]
numeric_cols <- setdiff(numeric_cols, c("state_code", "longitude", "latitude"))
# Loop through the columns and plot histograms
for (col in numeric_cols) {
  x <- aqs_data[[col]]
  
  # If max is much larger than the 99th percentile, filter the data for plotting
  p99 <- quantile(x, 0.99, na.rm = TRUE)
  if (max(x, na.rm = TRUE) > 2 * p99) {
    x <- x[x >= quantile(x, 0.01, na.rm = TRUE) & x <= p99]
  }
  hist(x, main = paste("Histogram of", col))
}
```

Bar Plots for categorical columns

```{r, bar-plots, echo = FALSE}
non_numeric_cols <- names(aqs_data)[sapply(aqs_data, Negate(is.numeric))]
non_numeric_cols <- setdiff(non_numeric_cols, c("id", "timestamp"))

for (col in non_numeric_cols) {
  col_data <- as.data.frame(table(aqs_data[[col]]))
  p <- ggplot(col_data, aes(x = reorder(Var1, -Freq), y = Freq)) +
    geom_bar(stat = "identity", fill = "steelblue") +
    labs(title = paste("Histogram of", col), x = col, y = "Frequency") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  print(p)
}
```
