---
title: "Exploratory Data Analysis: Weather Data" 
output: github_document
knit: (function(input, ...) {rmarkdown::render(input, output_dir = "../docs", )})
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(fig.path = "../docs/plots/")
options(scipen = 999) 
```

```{r, github-packages, echo=FALSE}
if (!"DataOverviewR" %in% rownames(installed.packages())) {
  suppressMessages({devtools::install_github("heba-razzak/DataOverviewR")})
}
```

```{r, load-libraries, message = FALSE, warning = FALSE, echo = FALSE}
library(dplyr)         # Data manipulation
library(DataOverviewR) # Data dictionary and summary
```

```{r, read-weather-csv, echo = FALSE}
filepath <- file.path("data", "raw", "weather.csv")
weather_data <- read.csv(filepath)
```

---

**Data Summary**

```{r, data-summ, echo = FALSE}
data_summary(weather_data, data_title = "Weather Summary")
```

---

Histograms for numerical columns

```{r, hist, echo = FALSE}
numeric_cols <- names(weather_data)[sapply(weather_data, is.numeric)]
numeric_cols <- setdiff(numeric_cols, c("lon", "lat"))
# Loop through the columns and plot histograms
for (col in numeric_cols) {
  x <- weather_data[[col]]
  
  # If max is much larger than the 99th percentile, filter the data for plotting
  p99 <- quantile(x, 0.99, na.rm = TRUE)
  if (max(x, na.rm = TRUE) > 2 * p99) {
    x <- x[x >= quantile(x, 0.01, na.rm = TRUE) & x <= p99]
  }
  hist(x, main = paste("Histogram of", col))
}
```

Bar Plots for categorical columns

```{r, bar-plots, echo = FALSE}
non_numeric_cols <- names(weather_data)[sapply(weather_data, Negate(is.numeric))]
non_numeric_cols <- setdiff(non_numeric_cols, c("timestamp"))

for (col in non_numeric_cols) {
  # Plot the histogram using barplot for categorical data
  barplot(table(weather_data[[col]]), main = paste("Histogram of", col), ylab = "Frequency")
}
```
