---
title: "Download PurpleAir Data" 
output: github_document
knit: (function(input, ...) {rmarkdown::render(input, output_dir = "../docs", )})
---

```{r}
  # Sensor index and active dates
  sensor_dates <- purpleair_data %>% 
    mutate(sensor_date = as.Date(time_stamp)) %>%
    select(sensor_index, sensor_date) %>% distinct()
  
  # Fire info
  fire_df <- fire %>% select(fire_id, fire_start, fire_end, fire_acres) %>% st_drop_geometry()
  
  # Join Purpleair sensors active date and fire info
  purpleair_fires_df <- pa_fire_dist_dir %>%
    left_join(sensor_dates, by = "sensor_index") %>%
    left_join(fire_df, by = "fire_id")
  
  # Create features for fire
  pafire <- purpleair_fires_df %>%
    mutate(fire_days1 = pmax(0, 1 + as.numeric(sensor_date - fire_start)),
           fire_days2 = ifelse(fire_days1 == 0 , 0, 1 + pmax(0,as.numeric(sensor_date - fire_end))),
           active_or_recent_fire = (fire_days2 == 1 | (fire_days2 > 1 & fire_days2 <= 8)),
           fire_distance = round(fire_distance),
           fire_acres = round(fire_acres)) %>% 
    filter(active_or_recent_fire) %>%
    select(sensor_index, sensor_date, fire_id, fire_days1, fire_days2, fire_distance, fire_acres, fire_direction)
  
  ## ADD DISTANCE FILTER ?
  
  # add fire features to dataset
  fire_data <- purpleair_data %>%
    mutate(sensor_date = as.Date(time_stamp)) %>%
    left_join(pafire, by = c("sensor_index" = "sensor_index", "sensor_date" = "sensor_date")) %>%
    select(-sensor_date) %>%
    replace_na(list(fire_days1 = 0, fire_days2 = 0, fire_distance = 0, fire_acres = 0, fire_direction = 0))
```

# FIRE CALCULATION
```{r}
# Create a combined score based on distance and recency
fire_impact <- purpleair_fires_df %>%
  mutate(
    recency_weight = 1 + max(0, fire_days1 - fire_days2),
    distance_weight = 1 / fire_distance,
    impact_score = recency_weight * distance_weight
  ) %>%
  group_by(sensor_index, sensor_date) %>%
  slice_max(impact_score)  # Keep fire with highest impact score for each sensor and date

```


```{r, setup, echo=FALSE}
knitr::opts_chunk$set(fig.path = "../docs/plots/", fig.dim = c(6, 4))
```

```{r, github-packages, echo=FALSE}
if (!"PurpleAirAPI" %in% rownames(installed.packages())) {
  suppressMessages({devtools::install_github("heba-razzak/PurpleAirAPI")})
}

if (!"DataOverviewR" %in% rownames(installed.packages())) {
  suppressMessages({devtools::install_github("heba-razzak/DataOverviewR")})
}
```

Load required libraries

```{r, load-libraries, message = FALSE, warning = FALSE}
library(dplyr)         # Data manipulation
```

```{r, echo = FALSE}
# CRS (coordinate reference system)
crs = 4326
```

**Download Sensor Data**\
Bold
Links:\
[Sensor fields](https://api.purpleair.com/#api-sensors-get-sensor-data)\
[Field Descriptions](https://community.purpleair.com/t/api-history-fields-descriptions/4652)

```{r, read-sensors-csv, echo = FALSE}
# Read sensors data
filepath <- file.path("data", "raw", "pa_sensors.csv")
pa_sensors <- read.csv(filepath)
pa_sf <- st_as_sf(pa_sensors, coords=c("longitude", "latitude"), crs = 4326)
```
---

**Data Dictionary**

```{r, data-dict1, echo = FALSE}
desc <- data_description(iris, 
                         var_desc = c("Sepal.Length" = "Sepal length",
                                      "Sepal.Width" = "Sepal width"))
data_dictionary(iris, 
                data_title = "Iris", 
                descriptions = desc, 
                hide = c("NA_Count", "NA_Percentage", "N_Unique", "top_n"))
```

```{r, data-dict-pa2, echo = FALSE}
data_dictionary(iris, 
                data_title = "Missing Values",
                hide = c("top_n", "Type", "N_Unique"))
```

**View data**

```{r, data-head, echo = FALSE}
knitr::kable(head(iris, 3), row.names = FALSE, format = "markdown")
```

---

**Data Summary**

```{r, data-summ, echo = FALSE}
data_summary(iris, data_title = "Iris Summary", var_types = c(Species = "date"))
```

If file exists
Write file

```{r, download-data}
filename <- paste0("filename", ".csv")
filepath <- file.path("data", "raw", filename)

if (!file.exists(filepath)) {
  print("test")
  # write.csv(df, file = filepath, row.names = FALSE)
  # st_write(sf_obj, filepath, driver = "GPKG", append=FALSE, quiet=TRUE)
}
```

Read file

```{r, read-csv, echo = FALSE}
filename <- paste0("filename", ".csv")
filepath <- file.path("data", "raw", filename)

# df <- read.csv(filepath)
# sf_obj <- st_read(filepath, quiet = TRUE)

```
